version: "3"

services:

#  apirest:
#    image: java8
#    build: .
#    entrypoint:  ["java", "-jar", "/shared-mar/mar-restservice/target/mar.restservice-1.0-SNAPSHOT-jar-with-dependencies.jar", "--port", "1234"]
#    volumes:
#      - ./:/shared-mar
#    ports:
#      - 1234:1234

#  notebook:
#    image: "jupyter/scipy-notebook"
#    ports:
#      - "8888:8888"
#    volumes:
#      - ..:/home/jovyan/MAR
#    user: root
#    environment:
#      - GRANT_SUDO=yes
#      - JUPYTER_ENABLE_LAB=yes
#    command: start-notebook.sh --NotebookApp.token=''   

  bdgenamenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: bdgenamenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./configuration/hadoop.env
    ports:
      - 127.0.0.1:50070:50070
      - 127.0.0.1:9000:9000

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "bdgenamenode:50070"
    env_file:
      - ./configuration/hadoop.env
    ports:
      - 127.0.0.1:50075:50075

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075"
    env_file:
      - ./configuration/hadoop.env
    ports:
      - 127.0.0.1:8088:8088

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./configuration/hadoop.env
    ports:
      - 127.0.0.1:8042:8042

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./configuration/hadoop.env
    ports:
      - 127.0.0.1:8188:8188
  
  zoo:
    image: zookeeper:3.4.10
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_MAX_CLIENT_CNXNS: 0
    ports:
      - 127.0.0.1:2181:2181

  hbase-master:
    image: dsevilla/hbase-master:1.0.0-hbase1.3.5
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./configuration/hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075 zoo:2181"
    ports:
      - 127.0.0.1:16010:16010
    volumes:
      - ./:/shared-mar
      
  hbase-region:
    image: dsevilla/hbase-regionserver:1.0.0-hbase1.3.5
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./configuration/hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 127.0.0.1:16030:16030
    

  hbase-thrift:
    image: dsevilla/hbase-thriftserver:1.0.0-hbase1.3.5
    container_name: hbase-thriftserver
    hostname: hbase-thriftserver
    env_file:
      - ./configuration/hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "bdgenamenode:50070 datanode:50075 zoo:2181 hbase-master:16010 hbase-regionserver:16030"
    ports:
      - 127.0.0.1:9090:9090

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
