services:
  mongo_db:
    restart: always
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - "mar_data:${REPO_MAR}"
    networks:
      services-network:
        aliases:
          - mongo_db

  api:
    depends_on:
      - mongo_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mongo_db
    networks:
      services-network:
        aliases:
          - graphql-api

volumes:
  mar_data:

networks:
  services-network:
    name: services-network
    driver: bridge